# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8VacBA9iLBnvmJHEGk1hwd6_F-7BaNL
"""

from ultralytics import YOLO
import cv2

# Load YOLOv8 model
model = YOLO("last.pt")

# Open camera or video
# If using webcam:
cap = cv2.VideoCapture(1)

# If you want video file instead:
# video_path = "video.mp4"
# cap = cv2.VideoCapture(video_path)

ret = True

while ret:
    ret, frame = cap.read()

    if ret:

        # Detect & track objects
        results = model.track(frame, persist=True)

        # Draw results on frame
        frame_ = results[0].plot()

        # Show output
        cv2.imshow("frame", frame_)

        # Press Q to quit
        if cv2.waitKey(25) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()